function [scenario, egoVehicle] = Straight_2Lane_Road()
% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 07-Jun-2022 12:59:17

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    310 0 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 -1.8375 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'EV');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [70 -1.8375 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [60 -1.8375 0;
    240 -1.8375 0];
speed = [15;15];
yaw =  [0;0];
smoothTrajectory(car1, waypoints, speed, 'Yaw', yaw);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [110 -1.8375 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [110 1.8375 0;
    310 1.8375 0];
speed = [17;17];
yaw =  [0;0];
smoothTrajectory(car2, waypoints, speed, 'Yaw', yaw);

